//// <auto-generated />
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using SLCM.Data;

//#nullable disable

//namespace SLCM.Migrations
//{
//    [DbContext(typeof(SLCMContext))]
//    partial class SLCMContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "9.0.11")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("SLCM.Models.Student", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("Email")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Name")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Phone")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Students");

//                    b.HasData(
//                        new
//                        {
//                            Id = 1,
//                            Email = "aisha@example.com",
//                            Name = "Aisha",
//                            Phone = "1111111111"
//                        },
//                        new
//                        {
//                            Id = 2,
//                            Email = "ravi@example.com",
//                            Name = "Ravi",
//                            Phone = "2222222222"
//                        },
//                        new
//                        {
//                            Id = 3,
//                            Email = "meena@example.com",
//                            Name = "Meena",
//                            Phone = "3333333333"
//                        });
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
